[package]
name = "ruis"
version = "0.1.0"
authors = ["Menno de Gier <mrdegier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "param_derive",
]

[dependencies]
param_derive = { path = "param_derive" }
hound = "3.4.0"
tui = "0.13"
termion = "1.5"
ringbuf = "0.2.2"
anyhow = "1.0.38"
lazy_static = "1.4.0"
camino = "1.0.4"
cpal = "0.13.3"
assert_no_alloc = "1.1.2"
triple_buffer = "6.0.0"
rand = "0.8.5"
num-traits = "0.2"
atomic_float = "0.1.0"
ulid = "1.0.0"
lru = "0.8.1"

[features]

[profile.release]
debug = true
