[package]
name = "ruis"
version = "0.1.0"
authors = ["Menno de Gier <mrdegier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
tui = "0.13"
termion = "1.5"
ringbuf = "0.2.2"
anyhow = "1.0.38"
atomic_float = "0.1.0"
lazy_static = "1.4.0"
camino = "1.0.4"
cpal = "0.13.3"